---
variables:
  GCT_CI_DOCKER_CONTEXT_PATH: $CI_PROJECT_DIR
  GCT_CI_DOCKERFILE_NAME: Dockerfile
  GCT_CI_IMAGE_NAME: image

.kaniko-build-template:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - export CONTAINER_TEST_IMAGE="${CI_REGISTRY_IMAGE}/${GCT_CI_IMAGE_NAME}:$CI_COMMIT_SHORT_SHA"
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $GCT_CI_DOCKER_CONTEXT_PATH --dockerfile $GCT_CI_DOCKER_CONTEXT_PATH/$GCT_CI_DOCKERFILE_NAME --destination $CONTAINER_TEST_IMAGE

.kaniko-release-template:
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  before_script:
    - export CONTAINER_TEST_IMAGE="${CI_REGISTRY_IMAGE}/${GCT_CI_IMAGE_NAME}:$CI_COMMIT_SHORT_SHA"
    - export CONTAINER_RELEASE_IMAGE="${CI_REGISTRY_IMAGE}/${GCT_CI_IMAGE_NAME}:latest"
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane cp ${CONTAINER_TEST_IMAGE} ${CONTAINER_RELEASE_IMAGE}
