git-tools-build:
  stage: build
  extends: .kaniko-build-template
  only:
    changes:
      - docker/git-tools/**/*
  variables:
    GCT_CI_DOCKER_CONTEXT_PATH: $CI_PROJECT_DIR/docker/git-tools
    GCT_CI_DOCKERFILE_NAME: Dockerfile
    GCT_CI_IMAGE_NAME: git-tools

git-tools-release-image-latest:
  stage: release
  only:
    refs:
      - master
      - tags
    changes:
      - docker/git-tools/**/*
  extends: .kaniko-release-template
  variables:
    GCT_CI_DOCKER_CONTEXT_PATH: $CI_PROJECT_DIR/docker/git-tools
    GCT_CI_DOCKERFILE_NAME: Dockerfile
    GCT_CI_IMAGE_NAME: git-tools