php-builder-7.4-build:
  stage: build
  extends: .kaniko-build-template
  only:
    changes:
      - docker/php-builder-7.4/**/*
  variables:
    GCT_CI_DOCKER_CONTEXT_PATH: $CI_PROJECT_DIR/docker/php-builder-7.4
    GCT_CI_DOCKERFILE_NAME: Dockerfile
    GCT_CI_IMAGE_NAME: php-builder-7.4

php-builder-7.4-release-image-latest:
  stage: release
  only:
    refs:
      - master
      - tags
    changes:
      - docker/php-builder-7.4/**/*
  extends: .kaniko-release-template
  variables:
    GCT_CI_DOCKER_CONTEXT_PATH: $CI_PROJECT_DIR/docker/php-builder-7.4
    GCT_CI_DOCKERFILE_NAME: Dockerfile
    GCT_CI_IMAGE_NAME: php-builder-7.4